name: macApp
options:
  bundleIdPrefix: jp.co.tsuqrea.designer_kmp_template
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true

configs:
  Debug: debug
  Release: release

configFiles:
  Debug: Configuration/Config.xcconfig
  Release: Configuration/Config.xcconfig

settings:
  base:
    ENABLE_USER_SCRIPT_SANDBOXING: false
    SWIFT_VERSION: "5.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic

targets:
  macApp:
    type: application
    platform: macOS
    sources:
      - path: macApp
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_NAME: $(inherited)
        INFOPLIST_FILE: macApp/Info.plist
        GENERATE_INFOPLIST_FILE: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_ASSET_PATHS: "\"macApp/Preview Content\""
        ENABLE_PREVIEWS: true
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    preBuildScripts:
      - name: Compile Kotlin Framework
        script: |
          if [ "YES" = "$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED" ]; then
            echo "Skipping Gradle build task invocation due to OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED environment variable set to \"YES\""
            exit 0
          fi
          cd "$SRCROOT/.."
          ./gradlew :shared:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
